### ISSUE TITLE
[build] AOF3_A_DEF.h is not unicode

### ISSUE THREAD

**Issue by y-ack** [Preppy/PalMod#25]
**encoding of Game/AOF3_A_DEF.h is extremely cp1252**:
`43 61 66 E9 | Café`

since PalMod.vcxproj specifies `<CharacterSet>Unicode</CharacterSet>`, msbuild invocation `& "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\MSBuild.exe" PalMod.sln` fails:
```
"...\PalMod\palmod\PalMod.sln" (default target) (1) ->
"...\PalMod\palmod\PalMod.vcxproj" (default target) (2) ->
(ClCompile target) ->
...\PalMod\palmod\Game\AOF3_A_DEF.h(643,7): error C2001: newline in constant [...\PalMod\palmod\PalMod.vcxproj]
```

converting the file to utf-8 resolves this
(e.g.) `iconv -f CP1252 -t UTF-8 Game/AOF3_A_DEF.h > Game/AOF3_A_DEF2.h; mv Game/AOF3_A_DEF2.h Game/AOF3_A_DEF.h`

**Comment by Preppy** [comment]
Interesting: I haven't been getting that error, but that's an easy fix.  Thanks for pointing it out!
